# Generated by Django 5.1.1 on 2024-09-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
